name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npx cypress run

      # If tests fail, upload screenshots for further investigation
      - name: Upload screenshots
        uses: actions/upload-artifact@v2
        if: failure()  # Only upload screenshots if the test fails
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      # If tests fail, upload videos for further investigation
      - name: Upload videos
        uses: actions/upload-artifact@v2
        if: failure()  # Only upload videos if the test fails
        with:
          name: cypress-videos
          path: cypress/videos

# # Notify Slack if tests fail
#   notify-slack:
#     if: failure()  # Only notify if the test fails
#     runs-on: ubuntu-latest

#     steps:
#       - name: Notify Slack
#         uses: 8398a7/action-slack@v3
#         with:
#           status: ${{ job.status }}
#           fields: repo,author
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}