name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npx cypress run

      # If tests fail, upload screenshots for further investigation
      - name: Upload screenshots
        uses: actions/upload-artifact@v3  # Updated to v3
        if: failure()  # Only upload screenshots if the test fails
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      # Optionally, upload videos for failed tests
      - name: Upload videos
        uses: actions/upload-artifact@v3  # Updated to v3
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
